name = "context-download"
main = "worker.js"
compatibility_date = "2026-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "RELEASES"
bucket_name = "context-releases"

[[kv_namespaces]]
binding = "PROFILES"
id = "298db151c04144498bf0f00cb6dbd8ba"

routes = [
  { pattern = "context.nikliolios.com", custom_domain = true }
]
